blank_issues_enabled: false
contact_links:
  - name: "\U0001F4AC Questions & Discussions"
    url: https://github.com/raman0c17/mocky/discussions
    about: Ask questions and share ideas with the community.
